package Kirjahylly.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import Kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.29 16:05:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjahyllyTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoistaKirja139 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaKirja139() throws SailoException {    // Kirjahylly: 139
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirja k1 = new Kirja(), k2 = new Kirja(), k3 = new Kirja(); 
    k1.kirjaaKirja(); k2.kirjaaKirja(); k3.kirjaaKirja(); 
    kirjahylly.lisaa(k1); kirjahylly.lisaa(k2); kirjahylly.lisaa(k3); 
    assertEquals("From: Kirjahylly line: 145", 3, kirjahylly.getKirjat()); 
    kirjahylly.poistaKirja(k1); 
    assertEquals("From: Kirjahylly line: 147", 2, kirjahylly.getKirjat()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHaku179 
   * @throws SailoException when error
   */
  @Test
  public void testHaku179() throws SailoException {    // Kirjahylly: 179
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirja k1 = new Kirja(); k1.parse("1|Internet     | Mikko Hyppönen | Otava     | Suomi| Kovakantinen| Muistelmat| 666| 2021|"); 
    Kirja k2 = new Kirja(); k2.parse("2|Testi        | Kari Kirjailija| WSOY      | Suomi| Pokkari     | Fantasia  | 201| 2001|"); 
    Kirja k3 = new Kirja(); k3.parse("3|Harry Potter | J.K.Rowling    | Bloomsbury| Suomi| Kovakantinen| Fantasia  | 352| 2002|"); 
    kirjahylly.lisaa(k1); kirjahylly.lisaa(k2); kirjahylly.lisaa(k3); 
    ArrayList<Kirja> loytyneet = new ArrayList<Kirja>(); 
    loytyneet = kirjahylly.haku("*ter*", 0); 
    assertEquals("From: Kirjahylly line: 189", 2, loytyneet.size()); 
  } // Generated by ComTest END
}