package Kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.29 16:07:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testKasvataTaulukkoa64 
   * @throws SailoException when error
   */
  @Test
  public void testKasvataTaulukkoa64() throws SailoException {    // Kirjat: 64
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(); 
    Kirja kirja2 = new Kirja(); 
    kirjat.lisaa(kirja1); kirjat.lisaa(kirja1); kirjat.lisaa(kirja1); kirjat.lisaa(kirja1); kirjat.lisaa(kirja1); 
    assertEquals("From: Kirjat line: 70", 5, kirjat.taulukonKoko()); 
    kirjat.lisaa(kirja2); 
    assertEquals("From: Kirjat line: 72", 6, kirjat.taulukonKoko()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa88 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa88() throws SailoException {    // Kirjat: 88
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    assertEquals("From: Kirjat line: 92", 0, kirjat.getLKM()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 93", 1, kirjat.getLKM()); 
    kirjat.lisaa(kirja2); assertEquals("From: Kirjat line: 94", 2, kirjat.getLKM()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 95", 3, kirjat.getLKM()); 
    assertEquals("From: Kirjat line: 96", kirja1, kirjat.annaKirja(0)); 
    assertEquals("From: Kirjat line: 97", kirja2, kirjat.annaKirja(1)); 
    assertEquals("From: Kirjat line: 98", kirja1, kirjat.annaKirja(2)); 
    assertEquals("From: Kirjat line: 99", false, kirjat.annaKirja(1) == kirja1); 
    assertEquals("From: Kirjat line: 100", true, kirjat.annaKirja(1) == kirja2); 
    try {
    assertEquals("From: Kirjat line: 101", kirja1, kirjat.annaKirja(3)); 
    fail("Kirjat: 101 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 102", 4, kirjat.getLKM()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 103", 5, kirjat.getLKM()); 
    Kirja kirja6 = new Kirja(); 
    kirjat.lisaa(kirja6); assertEquals("From: Kirjat line: 105", 6, kirjat.getLKM()); 
    assertEquals("From: Kirjat line: 106", 6, kirjat.taulukonKoko()); 
    kirjat.lisaa(kirja6); kirjat.lisaa(kirja6); kirjat.lisaa(kirja6); 
    kirjat.lisaa(kirja6); kirjat.lisaa(kirja6); 
  } // Generated by ComTest END
}