package Kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.28 14:02:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {


  // Generated by ComTest BEGIN
  /** 
   * testClone47 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone47() throws CloneNotSupportedException {    // Kirja: 47
    Kirja kirja = new Kirja(); 
    kirja.parse("Internet | Mikko Hyppönen "); 
    Kirja klooni = kirja.clone(); 
    assertEquals("From: Kirja line: 52", kirja.toString(), klooni.toString()); 
    kirja.parse("Näin opit leipomaan! | Naapurin Hans"); 
    assertEquals("From: Kirja line: 54", false, kirja.toString().equals(klooni.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKirjaaKirja85 */
  @Test
  public void testKirjaaKirja85() {    // Kirja: 85
    Kirja ekaKirja = new Kirja(); 
    Kirja tokaKirja = new Kirja(); 
    int k1, k2; 
    ekaKirja.kirjaaKirja(); 
    tokaKirja.kirjaaKirja(); 
    k1 = ekaKirja.getID(); 
    k2 = tokaKirja.getID(); 
    assertEquals("From: Kirja line: 93", k2-1, k1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetKentat171 */
  @Test
  public void testSetKentat171() {    // Kirja: 171
    Kirja kirja = new Kirja(); 
    kirja.setKentat(0, "Kirjan nimi"); 
    assertEquals("From: Kirja line: 174", "Kirjan nimi", kirja.getKentat(0)); 
    kirja.setKentat(4, "nauris"); 
    assertEquals("From: Kirja line: 176", "nauris", kirja.getKentat(4)); 
    kirja.setKentat(6, "247"); 
    assertEquals("From: Kirja line: 178", "247", kirja.getKentat(6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaNumerot223 */
  @Test
  public void testTarkistaNumerot223() {    // Kirja: 223
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 225", "Tähän kenttään voi asettaa vain positiivisia numeroita", kirja.tarkistaNumerot("-200", "vuosi")); 
    assertEquals("From: Kirja line: 226", "Tähän kenttään voi asettaa vain positiivisia numeroita", kirja.tarkistaNumerot("Haha olen hupsuttelija ja yritän laittaa kirjaimia numerokenttään hehee", "sivu")); 
    assertEquals("From: Kirja line: 227", null, kirja.tarkistaNumerot("200", "sivu")); 
  } // Generated by ComTest END
}