package Kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.29 15:38:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LisatietoTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone36 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone36() throws CloneNotSupportedException {    // Lisatieto: 36
    Lisatieto tieto = new Lisatieto(); 
    tieto.parse("6| 2| Lisätieto kirjasta| Lisätiedon sisältä"); 
    Lisatieto kopio = tieto.clone(); 
    assertEquals("From: Lisatieto line: 41", tieto.toString(), kopio.toString()); 
    tieto.parse("6|2|BLÖÖÖÖ|BLÄÄÄÄ"); 
    assertEquals("From: Lisatieto line: 43", false, kopio.toString().equals(tieto.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisatieto158 */
  @Test
  public void testLisatieto158() {    // Lisatieto: 158
    Lisatieto tieto = new Lisatieto(3); 
    assertEquals("From: Lisatieto line: 160", 3, tieto.getKirjanID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse171 */
  @Test
  public void testParse171() {    // Lisatieto: 171
    Lisatieto lisatieto = new Lisatieto(); 
    lisatieto.parse("6 | 9 | Hyllymbyvor | Rynkkäjynks |"); 
    assertEquals("From: Lisatieto line: 174", 6, lisatieto.getLisatietoID()); 
    assertEquals("From: Lisatieto line: 175", true, lisatieto.toString().startsWith("6|9|Hyllymbyvor|Rynkkäjynks|")); 
    lisatieto.kirjaa(); 
    int x = lisatieto.getLisatietoID(); 
    lisatieto.parse("" + (x+10)); 
    lisatieto.kirjaa(); 
    assertEquals("From: Lisatieto line: 180", x+11, lisatieto.getLisatietoID()); 
  } // Generated by ComTest END
}